import { Group } from "../../src/components/Group/Group";

// Sample data for 15 groups generated with GPT
export const sampleGroups: Group[] = [
    {
        name: "Tech Wizards",
        picture: "images/group/groupPic6.png",
        members: 9,
        public: true,
        uuid: "8F7D2C0B4A6E9135",
    },
    {
        name: "Travel Explorers",
        picture: "images/group/groupPic3.png",
        members: 7,
        public: false,
        uuid: "AFC1B92D6E5F0473",
    },
    {
        name: "Creative Minds",
        picture: "images/group/groupPic2.png",
        members: 4,
        public: true,
        uuid: "DECA71F592B83D06",
    },
    {
        name: "Sunday Lunch",
        picture: "images/group/groupPic8.png",
        members: 3,
        public: false,
        uuid: "7A4B9D0F3C1E5826",
    },
    {
        name: "Nature Enthusiasts",
        picture: "images/group/groupPic4.png",
        members: 6,
        public: true,
        uuid: "3E6F1D5B7C2A8409",
    },
    {
        name: "Food Lovers",
        picture: "images/group/groupPic1.png",
        members: 5,
        public: false,
        uuid: "F71C09D6E2A4B8C5",
    },
    {
        name: "Hiking Adventures",
        picture: "images/group/groupPic7.png",
        members: 8,
        public: true,
        uuid: "82E0B9D4C7F5A613",
    },
    {
        name: "Music Fanatics",
        picture: "images/group/groupPic5.png",
        members: 12,
        public: false,
        uuid: "1C9A84E3B60D75FA",
    },
    {
        name: "Cooking Club",
        picture: "images/group/groupPic1.png",
        members: 10,
        public: true,
        uuid: "6D5A0C8F7B2E3491",
    },
    {
        name: "Book Club",
        picture: "images/group/groupPic3.png",
        members: 14,
        public: false,
        uuid: "B4F8E35A1D792C06",
    },
    {
        name: "Photography Enthusiasts",
        picture: "images/group/groupPic6.png",
        members: 13,
        public: true,
        uuid: "04B5E7F9D2C813A6",
    },
    {
        name: "Film Buffs",
        picture: "images/group/groupPic4.png",
        members: 11,
        public: false,
        uuid: "5D1E7F8A30B249C6",
    },
    {
        name: "Fitness Enthusiasts",
        picture: "images/group/groupPic8.png",
        members: 15,
        public: true,
        uuid: "9D0B3C4E2A7F1865",
    },
    {
        name: "Gaming Guild",
        picture: "images/group/groupPic4.png",
        members: 2,
        public: false,
        uuid: "2E1A47FC0B5D8369",
    },
    {
        name: "Art Creators",
        picture: "images/group/groupPic5.png",
        members: 1,
        public: true,
        uuid: "3A8F1D6B0C2497E5",
    },
];
